push_button:
  name: Push Button
  description: Simulate pushing a hardware button on the NanoKVM device.
  fields:
    button_type:
      name: Button Type
      description: The type of button to push (power or reset).
      required: true
      selector:
        select:
          options:
            - "power"
            - "reset"
    duration:
      name: Duration
      description: The duration to hold the button in milliseconds (100-5000).
      default: 100
      selector:
        number:
          min: 100
          max: 5000
          unit_of_measurement: ms

paste_text:
  name: Paste Text
  description: Paste text via HID keyboard simulation.
  fields:
    text:
      name: Text
      description: The text to paste. Only ASCII printable characters are supported.
      required: true
      selector:
        text:
          multiline: true

reboot:
  name: Reboot System
  description: Reboot the NanoKVM device.

reset_hdmi:
  name: Reset HDMI
  description: Reset the HDMI connection (relevant for PCIe version).

reset_hid:
  name: Reset HID
  description: Reset the HID subsystem.

wake_on_lan:
  name: Wake on LAN
  description: Send a Wake-on-LAN packet to the specified MAC address.
  fields:
    mac:
      name: MAC Address
      description: The MAC address to send the Wake-on-LAN packet to.
      required: true
      example: "00:11:22:33:44:55"
      selector:
        text:
